#!/usr/bin/env python3
"""Rasterise ASCII glyphs from a font into runtime/font_data.c (alpha bitmaps + metrics).
usage: make_font.py Inter-Medium.otf Inter-Bold.otf"""
import sys
from PIL import ImageFont
regular,bold=sys.argv[1],sys.argv[2]
SIZES=[(regular,15),(bold,15),(bold,22),(bold,38)]
out=['/* GENERATED by tools/make_font.py from Inter (SIL Open Font License 1.1). */','#include "font.h"','']
blob,fonts=[],[]
for fi,(path,px) in enumerate(SIZES):
 f=ImageFont.truetype(path,px);asc,desc=f.getmetrics();glyphs=[]
 for c in range(32,127):
  ch=chr(c);l,t,r,b=f.getbbox(ch,anchor='ls');w,h=max(0,r-l),max(0,b-t);off=len(blob)
  if w and h:
   im=f.getmask(ch,mode='L');ml,mt,mr,mb=f.getbbox(ch,anchor='ls');iw,ih=im.size;data=list(im);w,h=iw,ih;blob.extend(data)
  glyphs.append((off,w,h,l,t,round(f.getlength(ch))))
 fonts.append((asc+desc,asc,glyphs))
out.append(f'const unsigned char font_blob[{len(blob)}] = {{')
for i in range(0,len(blob),40):out.append(','.join(str(v) for v in blob[i:i+40])+',')
out.append('};');out.append('const FontDef font_defs[4] = {')
for lh,asc,g in fonts:
 out.append(f'  {{ {lh}, {asc}, {{')
 for off,w,h,l,t,adv in g:out.append(f'    {{{off},{w},{h},{l},{t},{adv}}},')
 out.append('  }},')
out.append('};');open('runtime/font_data.c','w').write('\n'.join(out)+'\n');print(len(blob),'bytes of glyph data')