#!/usr/bin/env python3
"""Game Boy SM83 static recompiler and interpreter generator."""
import argparse
import os
import sys
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sm83 import decode

VECTORS = [0x00,0x08,0x10,0x18,0x20,0x28,0x30,0x38,0x40,0x48,0x50,0x58,0x60]
ENTRY = 0x100

def decode_at(rom, pc):
    b1 = rom[pc + 1] if pc + 1 < len(rom) else 0
    b2 = rom[pc + 2] if pc + 2 < len(rom) else 0
    return decode(rom[pc], b1, b2, pc=pc)

def discover(rom, roots):
    insns = {}
    labels = set(roots)
    pending = list(reversed(sorted(roots)))
    while pending:
        pc = pending.pop()
        while 0 <= pc < len(rom) and pc not in insns:
            ins = decode_at(rom, pc)
            insns[pc] = ins
            nxt = pc + ins.length
            if ins.kind in ("jp", "call", "rst") and ins.target < len(rom):
                labels.add(ins.target)
                pending.append(ins.target)
            if ins.kind == "jp" and ins.cond is None:
                break
            if ins.kind in ("ret", "reti", "jphl", "illegal") and ins.cond is None:
                break
            if ins.kind in ("call", "rst") and nxt < len(rom):
                labels.add(nxt)
            if ins.kind == "jp" and ins.cond is not None and nxt < len(rom):
                labels.add(nxt)
            pc = nxt
    return insns, labels

def emit_lifted(insns, labels):
    addrs = sorted(insns)
    physical = {a:(addrs[i+1] if i+1 < len(addrs) else None) for i,a in enumerate(addrs)}
    for a in addrs:
        ins = insns[a]
        flows = ins.kind in ("seq","halt","rst") or ins.cond is not None
        if ins.kind in ("jp","ret","reti","jphl","illegal") and ins.cond is None:
            flows = ins.kind == "rst"
        if flows and a + ins.length in insns and physical[a] != a + ins.length:
            labels.add(a + ins.length)

    def go(t):
        return f"goto L_{t:04X};" if t in insns else f"cpu.pc = 0x{t:04X}; goto dispatch;"

    out = [
        "/* GENERATED by tools/recomp.py - do not edit. */",
        '#include "sm83.h"',
        "",
        "void recomp_run(void)",
        "{",
        "dispatch:",
        "    switch (cpu.pc) {"
    ]
    for t in sorted(labels):
        if t in insns:
            out.append(f"    case 0x{t:04X}: goto L_{t:04X};")
    out += ["    default: goto miss;", "    }", "miss:", "    recomp_miss(cpu.pc);",
            "    cpu_step_checked();", "    goto dispatch;", "irq:", "    cpu_service_irq();",
            "    goto dispatch;"]
    for a in addrs:
        ins = insns[a]
        if a in labels:
            out.append(f"L_{a:04X}:;")
        nxt = (a + ins.length) & 0xFFFF
        out.append(f"    /* {a:04X} {ins.text} */")
        k = ins.kind
        if k == "illegal":
            out.append(f"    cpu_lockup(0x{ins.op:02X}, 0x{a:04X});")
        elif k in ("seq","halt"):
            if ins.body:
                out.append(f"    {ins.body}")
            out.append(f"    tick({4 if k == 'halt' else ins.taken});" + (" cpu_halt();" if k == "halt" else "") + f" NEXT(0x{nxt:04X});")
            if a + ins.length not in insns or physical[a] != a + ins.length:
                out.append("    " + go(nxt))
        elif k == "jp":
            if ins.cond is None:
                out.append(f"    tick({ins.taken}); NEXT(0x{ins.target:04X}); {go(ins.target)}")
            else:
                out.append(f"    if ({ins.cond}) {{ tick({ins.taken}); NEXT(0x{ins.target:04X}); {go(ins.target)} }}")
                out.append(f"    tick({ins.nt}); NEXT(0x{nxt:04X});")
                if a + ins.length not in insns or physical[a] != a + ins.length:
                    out.append("    " + go(nxt))
        elif k in ("call","rst"):
            pre = f"push16(0x{nxt:04X}); tick({ins.taken}); NEXT(0x{ins.target:04X}); {go(ins.target)}"
            if ins.cond is None:
                out.append("    " + pre)
            else:
                out.append(f"    if ({ins.cond}) {{ {pre} }}")
                out.append(f"    tick({ins.nt}); NEXT(0x{nxt:04X});")
                if a + ins.length not in insns or physical[a] != a + ins.length:
                    out.append("    " + go(nxt))
        elif k == "ret":
            if ins.cond is None:
                out.append("    cpu.pc = pop16(); tick(%d); NEXT(cpu.pc); goto dispatch;" % ins.taken)
            else:
                out.append(f"    if ({ins.cond}) {{ cpu.pc = pop16(); tick({ins.taken}); NEXT(cpu.pc); goto dispatch; }}")
                out.append(f"    tick({ins.nt}); NEXT(0x{nxt:04X});")
                if a + ins.length not in insns or physical[a] != a + ins.length:
                    out.append("    " + go(nxt))
        elif k == "reti":
            out.append(f"    cpu.ime = 1; cpu.pc = pop16(); tick({ins.taken}); NEXT(cpu.pc); goto dispatch;")
        elif k == "jphl":
            out.append("    cpu.pc = HL(); tick(4); NEXT(cpu.pc); goto dispatch;")
    mask = bytearray(0x1000)
    for a, ins in insns.items():
        for n in range(ins.length):
            if a + n < 0x8000:
                mask[(a+n)//8] |= 1 << ((a+n)&7)
    out.append("}")
    out.append("")
    out.append("const unsigned char recomp_code_mask[0x1000] = {")
    for i in range(0, 0x1000, 32):
        out.append("    " + ",".join(str(v) for v in mask[i:i+32]) + ",")
    out.append("};")
    return "\n".join(out) + "\n"

def emit_interp():
    out = ['/* GENERATED by tools/recomp.py - do not edit. */', '#include "sm83.h"', "",
           "void cpu_step(void)", "{", "    uint8_t op = rd8(cpu.pc);",
           "    if (wide_intercept_sml2(op)) return;", "    switch (op) {"]
    def body(ins):
        pre = ""
        if ins.length == 2:
            pre = "uint8_t n8 = rd8((uint16_t)(cpu.pc + 1)); (void)n8; "
        elif ins.length == 3:
            pre = "uint16_t n16 = (uint16_t)(rd8((uint16_t)(cpu.pc + 1)) | (rd8((uint16_t)(cpu.pc + 2)) << 8)); "
        k = ins.kind
        if k == "illegal":
            return "cpu_lockup(op, cpu.pc);"
        if k in ("seq","halt"):
            return pre + ins.body + f" cpu.pc = (uint16_t)(cpu.pc + {ins.length}); tick({ins.taken});" + (" cpu_halt();" if k == "halt" else "")
        if k == "jp":
            target = f"0x{ins.target:04X}" if isinstance(ins.target, int) else ins.target
            if ins.cond is None:
                return pre + f"cpu.pc = {target}; tick({ins.taken});"
            return pre + f"if ({ins.cond}) {{ cpu.pc = {target}; tick({ins.taken}); }} else {{ cpu.pc = (uint16_t)(cpu.pc + {ins.length}); tick({ins.nt}); }}"
        if k in ("call","rst"):
            target = f"0x{ins.target:04X}" if isinstance(ins.target, int) else ins.target
            if ins.cond is None:
                return pre + f"cpu.pc = (uint16_t)(cpu.pc + {ins.length}); push16(cpu.pc); cpu.pc = {target}; tick({ins.taken});"
            return pre + f"cpu.pc = (uint16_t)(cpu.pc + {ins.length}); if ({ins.cond}) {{ push16(cpu.pc); cpu.pc = {target}; tick({ins.taken}); }} else tick({ins.nt});"
        if k == "ret":
            if ins.cond is None:
                return f"cpu.pc = pop16(); tick({ins.taken});"
            return f"if ({ins.cond}) {{ cpu.pc = pop16(); tick({ins.taken}); }} else {{ cpu.pc = (uint16_t)(cpu.pc + 1); tick({ins.nt}); }}"
        if k == "reti":
            return f"cpu.ime = 1; cpu.pc = pop16(); tick({ins.taken});"
        if k == "jphl":
            return "cpu.pc = HL(); tick(4);"
        raise RuntimeError(k)
    for op in range(256):
        if op == 0xCB:
            out += ["    case 0xCB: {", "        uint8_t n8 = rd8((uint16_t)(cpu.pc + 1));",
                    "        switch (n8) {"]
            for cb in range(256):
                ins = decode(0xCB, cb, 0, dyn=True)
                out.append(f"        case 0x{cb:02X}: {ins.body} cpu.pc = (uint16_t)(cpu.pc + 2); tick({ins.taken}); break;")
            out += ["        }", "        break;", "    }"]
        else:
            ins = decode(op, dyn=True)
            out.append(f"    case 0x{op:02X}: {{ {body(ins)} break; }}")
    out += ["    }", "}", "", "/* Interpreter-only builds have no statically lifted code. */", "const unsigned char recomp_code_mask[0x1000] = {0};"]
    return "\n".join(out) + "\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("rom")
    ap.add_argument("-o","--out",default="generated")
    ap.add_argument("--roots")
    ap.add_argument("--noreturn-rst",default="")
    ap.add_argument("--listing",action="store_true")
    ap.add_argument("--interp-only",action="store_true")
    ap.add_argument("--name")
    args = ap.parse_args()
    rom = open(args.rom,"rb").read()
    if len(rom) > 0x8000 and not args.interp_only:
        raise SystemExit(f"error: ROM is {len(rom)} bytes; use --interp-only for mapper/banked ROMs.")
    if len(rom) < 0x8000:
        rom += b"\xff" * (0x8000-len(rom))
    roots = VECTORS + [ENTRY]
    if args.roots and os.path.exists(args.roots):
        roots += [int(x,16) for x in open(args.roots).read().split() if x.strip()]
    os.makedirs(args.out,exist_ok=True)
    if args.interp_only:
        code = '/* GENERATED */\n#include "gb.h"\nvoid recomp_run(void) { run_interpreter(); }\n'
        insns, labels = {}, set()
    else:
        insns, labels = discover(rom, roots)
        code = emit_lifted(insns, labels)
    open(os.path.join(args.out,"game.c"),"w").write(code)
    open(os.path.join(args.out,"interp.c"),"w").write(emit_interp())
    crc = zlib.crc32(rom) & 0xffffffff
    title = bytes(rom[0x134:0x144]).split(b"\0")[0].decode("ascii","replace")
    name = args.name or title.title()
    open(os.path.join(args.out,"game_info.h"),"w").write(
        f'/* GENERATED */\n#define ROM_CRC32 0x{crc:08X}u\n#define ROM_TITLE "{title}"\n#define GAME_NAME "{name}"\n')
    if args.listing:
        with open(os.path.join(args.out,"listing.txt"),"w") as f:
            for pc in sorted(insns):
                f.write(f'{pc:04X}{"*" if pc in labels else " "} {insns[pc].text}\n')
    print(f"{args.rom}: crc32 {crc:08X}; {len(insns)} instructions; {'interpreter-only' if args.interp_only else 'static recompile'}")

if __name__ == "__main__":
    main()
